[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "heart_failure"
version = "0.0.1"
description = "predicting heart disease events"
authors = [
  { name = "Tatsiana Kozlova" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
dependencies = [
    "ipython>=9.14.1",
    "loguru",
    "matplotlib>=3.10.9",
    "numpy>=2.4.6",
    "pandas>=2.3.3",
    "pip",
    "plotly>=6.8.0",
    "python-dotenv",
    "ruff",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.6",
    "tqdm",
    "typer",
    "mlflow>=3.10.1",
    "ipywidgets>=8.1.8",
    "optuna>=4.9.0",
    "catboost>=1.2.10",
    "xgboost>=3.3.0",
]
requires-python = "~=3.13.0"


[tool.ruff]
line-length = 99
src = ["heart_failure"]
include = ["pyproject.toml", "heart_failure/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["heart_failure"]
force-sort-within-sections = true

