from heart_failure.config.config import (
    SEX,
    RESTING_ECG,
    CHEST_PAIN_TYPE,
    ST_SLOPE,
    AGE,
    CHOLESTEROL,
    MAX_HR,
    FASTING_BS,
    EXERCISE_ANGINA,
)

TEST_SIZE = 0.2
RANDOM_STATE = 42
TE_CV = 5
TE_FEATURES = [RESTING_ECG, CHEST_PAIN_TYPE, ST_SLOPE]
BINARIZED_FEATURES = [AGE]
BINARY_CAT_FEATURES = [SEX, FASTING_BS, EXERCISE_ANGINA]
Z_SCORED_FEATURES = [CHOLESTEROL, MAX_HR]
OLDPEAK_TE_FEATURES = [ST_SLOPE, EXERCISE_ANGINA, CHEST_PAIN_TYPE]
MAX_HR_TE_FEATURES = [RESTING_ECG]
FASTING_BS_TE_FEATURES = [ST_SLOPE, CHEST_PAIN_TYPE, EXERCISE_ANGINA]
